source "https://rubygems.org"

gem "byebug", "~> 11.1", :groups => [:development, :test]
gem "coffee-rails", "~> 5.0"
gem "dalli", "~> 3.2", :group => :development
gem "jbuilder", "~> 2.11"
gem "jquery-rails", "~> 4.5"
gem "jwt", "~> 2.7"
gem "mimemagic", github: "mimemagicrb/mimemagic", ref: "01f92d86d15d85cfd0f20dabd025dcbd36a8a60f"
gem "rack-cors", "~> 2.0"
gem "rails", "~> 7.0"
gem "rubocop", "~> 1.52", :group => :development
gem "sass-rails", "~> 6.0"
gem "sdoc", "~> 2.6", :group => :doc
gem "sorbet", "~> 0.5.10871", :group => :development
gem "sorbet-runtime", "~> 0.5.10871"
gem "tapioca", "~> 0.11.6", :group => :development
gem "turbolinks", "~> 5.2"
gem "tzinfo-data", "~> 1.2023"
gem "uglifier", "~> 4.2"
gem "uuid", "~> 2.3"
gem "web-console", "~> 4.2", :groups => [:development, :test]
gem "webrick", "~> 1.8"
