version: "3.8"

services:

  document-server:
    container_name: document-server
    image: onlyoffice/documentserver:7.3.3.50
    expose:
      - "80"
    environment:
      - JWT_ENABLED=false

  example:
    container_name: example
    build:
      context: .
      target: example
    expose:
      - "80"
    environment:
      - EXAMPLE_URL=http://proxy:8080
      - PORT=80
      - SITE_URL=http://localhost:3000/

  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    ports:
      - "8080:8080"
      - "3000:3000"
