name: Artifact Python

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/python/**']
  pull_request:
    branches: [master]
    paths: ['web/documentserver-example/python/**']

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          git submodule update --init --recursive
          cd ./web/documentserver-example/python
          mkdir -p ./deploy/'Python Example'
          rsync -av --exclude='deploy' ./ ./deploy/'Python Example'
          rm -rf ./deploy/'Python Example'/assets/document-formats/.git
          rm -rf ./deploy/'Python Example'/assets/document-templates/.git
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python.Example
          path: ${{ github.workspace }}/web/documentserver-example/python/deploy