name: PHPCs

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/php/**']
  pull_request:
    branches: [master, develop]
    paths: ['web/documentserver-example/php/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/documentserver-example/php
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcs
          
      - name: Lint
        run: phpcs src index.php
