name: Lint Spring

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/java-spring/**']
  pull_request:
    branches: [master, develop]
    paths: ['web/documentserver-example/java-spring/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/documentserver-example/java-spring
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Run linter
        run: |
          mvn -version
          mvn package