name: PyLint

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/python/**']
  pull_request:
    branches: [master, develop]
    paths: ['web/documentserver-example/python/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/documentserver-example/python
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: |
          make dev

      - name: Lint Flake8
        run: |
          make lint

      # TODO: Configure mypy
      # - name: Types mypy
      #   run: |
      #     make types
