name: Golangci

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/go/**']
  pull_request:
    branches: [master, develop]
    paths: ['web/documentserver-example/go/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/documentserver-example/go
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' 

      - name: Lint Golangci
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run